version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - Vurolock
  ignore:
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - Vurolock
  ignore:
  - dependency-name: cheerio
    versions:
    - 1.0.0-rc.5
  - dependency-name: lodash
    versions:
    - 4.17.20
